config/routes.rb
Ruleperfect::Application.routes.draw do
  get "static_pages/about"
  
  resources :rules
  resources :posts
  
  root 'posts#new'
  # root 'static_pages#home'
  
  get   'posts/new/:topic',to: 'posts#new', as: :topic
  get   'rules/:subject',to: 'rules#index', as: :subject
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :rule
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @rule = Rule.find_by(id: @post.rule_id)
    @statement = @rule.statement
    @keywords = @rule.keywords.split(', ')
  end

  # GET /posts/new
  def new
    @post = Post.new

    @contracts_remaining = Rule.where(:topic => "contracts", :correct => nil).count.to_s
    @evidence_remaining = Rule.where(:topic => "evidence", :correct => nil).count.to_s
    @torts_remaining = Rule.where(:topic => "torts", :correct => nil).count.to_s
    @property_remaining = Rule.where(:topic => "property", :correct => nil).count.to_s
    @community_remaining = Rule.where(:topic => "community property", :correct => nil).count.to_s
    @crim_remaining = Rule.where(:topic => "crim", :correct => nil).count.to_s
    @wills_remaining = Rule.where(:topic => "wills", :correct => nil).count.to_s
    @civpro_remaining = Rule.where(:topic => "civpro", :correct => nil).count.to_s
    @business_remaining = Rule.where(:topic => "business", :correct => nil).count.to_s
    @pr_remaining = Rule.where(:topic => "pr", :correct => nil).count.to_s
    @conlaw_remaining = Rule.where(:topic => "conlaw", :correct => nil).count.to_s

    
    if params[:topic]
      @rule = Rule.where(:topic => params[:topic], :correct => nil).order("Random()").first
      if @rule 
        @rule_id = @rule.id
      end
      @remaining = Rule.where(:topic => params[:topic], :correct => nil).count.to_s
    else
      @rule_id = rand(1...488)  
    end
    
    @rule = Rule.find_by(id: @rule_id)
    @rules = Rule.order(:name)
  end
  

  # GET /posts/1/edit
  def edit
  end

  def perfect(z) 
    if z.empty?
      @pefect = true
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
          

    respond_to do |format|
      if @post.save
        @rule = Rule.find_by(id: @post.rule_id)
        @topic = @rule.topic
        @statement = @rule.statement
        @keywords = @rule.keywords.gsub(",", "").split(' ')
        
        a = @rule.keywords.gsub(",", "").split(' ')
        b = @post.content.gsub(",", "").gsub(".", "")
        c = b.split(" ")
        z = a - c
                
        if z.empty?
          @status = true
          @rule = Rule.find_by(id: @post.rule_id)
          @rule.toggle!(:correct)
          format.html { redirect_to new_post_path(:topic => @topic), notice: 'CORRECT! ' + @keywords.to_s }
          format.json { render action: 'show', status: :created, location: @post }
        else
          @status = false
          format.html { redirect_to @post, notice: 'INCORRECT! Keywords required:' }
          format.json { render action: 'show', status: :created, location: @post }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      #@topic = Post.find(params[:topic])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :rule_id)
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    if params[:subject]
      @rules = Rule.where(:topic => params[:subject])
    else
      @rules = Rule.all
    end
  end
    
  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:name, :statement, :keywords, :topic)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>ruleperfect | <%= yield(:title) %></title>  
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="header">
	[logo][login]
  </div>

  <center>
    <div id="content">
      <%= yield %>
    </div>
  </center>

<script>
function pressed(e) {
    if ( (window.event ? event.keyCode : e.which) == 13) { 
        document.forms[0].submit() 
    }
}
</script>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
	<%= f.hidden_field :rule_id, value: @rule_id %>
  </div>
  <div class="field">
    <%= f.text_area :content, :cols => 70, :rows => 16, autofocus: true, :onKeyDown => "pressed(event)"  %>
  </div>
  <div class="actions">
    <%= f.submit "Submit!" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Rule</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.rule_id %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= link_to_unless_current('Contracts (' + @contracts_remaining +')', new_post_path(:topic => "contracts")) %> | 
<%= link_to_unless_current('Evidence (' + @evidence_remaining +')', new_post_path(:topic => "evidence")) %> | 
<%= link_to_unless_current('Torts (' + @torts_remaining +')', new_post_path(:topic => "torts")) %> | 
<%= link_to_unless_current('Property (' + @property_remaining +')', new_post_path(:topic => "property")) %> | 
<%= link_to_unless_current('Community Property (' + @community_remaining +')', new_post_path(:topic => "community property")) %> | 
<%= link_to_unless_current('Crim & CrimPro (' + @crim_remaining +')', new_post_path(:topic => "crim")) %> | 
<%= link_to_unless_current('Wills & Trusts (' + @wills_remaining +')', new_post_path(:topic => "wills")) %> |

<%= link_to_unless_current('CivPro (' + @civpro_remaining +')', new_post_path(:topic => "civpro")) %> | 
<%= link_to_unless_current('Business Associations (' + @business_remaining +')', new_post_path(:topic => "business")) %> | 
<%= link_to_unless_current('PR (' + @pr_remaining +')', new_post_path(:topic => "pr")) %> | 
<%= link_to_unless_current('ConLaw (' + @conlaw_remaining +')', new_post_path(:topic => "conlaw")) %> 


<p id="notice" style="<%= @status %>"><%= notice %></p>

<p><%= @remaining %> remaining</p>

<p id="rule" align="left"><strong><% if @rule %><%= @rule.name %><% end %></strong></p>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/posts/show.html.erb
<% if !@status %>
	<p class="wrong">INCORRECT! Missing keywords:</p>
	<% elsif @status %>
	<p id="notice">Correct!</p>
<% end %>

  <% if @keywords %>
	<% @keywords.each do |keyword| %>
		<strong><%= keyword %><br></strong>
	<% end %>
  <% end %>
</p>

<p>
  <%= @statement %>
  
</p>



<%= link_to 'Back', new_post_path %>

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :statement %><br>
    <%= f.text_area :statement, :cols => 70, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_area :keywords, :cols => 70, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/contracts.html.erb
<h1>Listing rules</h1>

<br>
<%= link_to 'New Rule', new_rule_path %>
<br><br>

<%= link_to_unless_current 'All', rules_path %>

<%= link_to_unless_current('Contracts', contracts_rules_path) %>

<%= link_to_unless_current('Evidence', evidence_rules_path) %>


<%= link_to_unless_current('Torts', torts_rules_path) %>
<%= link_to_unless_current('Property', property_rules_path) %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Statement</th>
      <th>Keywords</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.name %></td>
        <td><%= rule.statement %></td>
        <td><%= rule.keywords %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/evidence.html.erb
<h1>Listing rules</h1>

<%= link_to_unless_current 'All', rules_path %>

<a href="">Contracts</a>

<%= link_to_unless_current('Evidence', evidence_rules_path) %>

<a href="">Property</a>

<a href="">Torts</a>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Statement</th>
      <th>Keywords</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.name %></td>
        <td><%= rule.statement %></td>
        <td><%= rule.keywords %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/index.html.erb
<h1>Listing rules</h1>

<br>
<%= link_to 'New Rule', new_rule_path %>
<br><br>

<%= link_to 'All', rules_path %> |

<%= link_to_unless_current('Contracts', rules_path(:subject => "contracts")) %> | 
<%= link_to_unless_current('Evidence', rules_path(:subject => "evidence")) %> | 
<%= link_to_unless_current('Torts', rules_path(:subject => "torts")) %> | 
<%= link_to_unless_current('Property', rules_path(:subject => "property")) %> | 
<%= link_to_unless_current('Community Property', rules_path(:subject => "community property")) %> | 
<%= link_to_unless_current('Crim & CrimPro', rules_path(:subject => "crim")) %> <br>
<%= link_to_unless_current('Wills & Trusts', rules_path(:subject => "wills")) %> | 
<%= link_to_unless_current('CivPro', rules_path(:subject => "civpro")) %> | 
<%= link_to_unless_current('Business Associations', rules_path(:subject => "business")) %> | 
<%= link_to_unless_current('PR', rules_path(:subject => "pr")) %> | 
<%= link_to_unless_current('ConLaw', rules_path(:subject => "conlaw")) %> 

<br>
<br>
Rules: <%= @rules.count.to_s %>

<br>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Statement</th>
      <th>Keywords</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.name %></td>
        <td><%= rule.statement %></td>
        <td><%= rule.keywords %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rules/new.html.erb
<h1>New rule</h1>



<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/property.html.erb
<h1>Listing rules</h1>

<br>
<%= link_to 'New Rule', new_rule_path %>
<br><br>


<%= link_to_unless_current('Contracts', contracts_rules_path) %>

<%= link_to_unless_current('Evidence', evidence_rules_path) %>


<%= link_to_unless_current('Torts', torts_rules_path) %>
<%= link_to_unless_current('Property', property_rules_path) %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Statement</th>
      <th>Keywords</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.name %></td>
        <td><%= rule.statement %></td>
        <td><%= rule.keywords %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>


  <strong>Topic:</strong>
  <%= @rule.topic %>
</p>
<p>
  <strong>Name:</strong>
  <%= @rule.name %>
</p>

<p>
  <strong>Statement:</strong>
  <%= @rule.statement %>
</p>
<p>
  <strong>Keywords:</strong>
  <%= @rule.keywords %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>

app/views/rules/torts.html.erb
<h1>Listing rules</h1>

<br>
<%= link_to 'New Rule', new_rule_path %>
<br><br>


<%= link_to_unless_current('Contracts', contracts_rules_path) %>

<%= link_to_unless_current('Evidence', evidence_rules_path) %>


<%= link_to_unless_current('Torts', torts_rules_path) %>
<%= link_to_unless_current('Property', property_rules_path) %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Statement</th>
      <th>Keywords</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.name %></td>
        <td><%= rule.statement %></td>
        <td><%= rule.keywords %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is the about page for 
  <a href="http://www.ruleperfect.com/">ruleperfect</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>RulePerfect</h1>
<p>
		
  This is the home page for 
  <a href="http://www.ruleperfect.com/">ruleperfect</a>.
</p>